/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "teal-primary": "#006D5B",
        "teal-dark": "#004F42",
        "teal-light": "#E8F5F2",
        lavender: "#E0E7FF",
        "bg-soft": "#F8FAFC",
        "bg-white": "#FFFFFF",
        "text-dark": "#1E293B",
        "text-muted": "#64748B",
        "border-light": "#E2E8F0",
        "on-secondary-fixed": "#131b2e",
        "secondary-fixed-dim": "#bec6e0",
        "primary-fixed-dim": "#6bd8cb",
        "surface-container-highest": "#d3e4fe",
        outline: "#6d7a77",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#f3fffc",
        background: "#f8f9ff",
        "tertiary-fixed": "#d8e5e2",
        "primary-fixed": "#89f5e7",
        "surface-tint": "#006a61",
        primary: {
          DEFAULT: "#00685f",
          50: "#ecfdf5",
          100: "#d1fae5",
          200: "#a7f3d0",
          300: "#6ee7b7",
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
          700: "#047857",
          800: "#065f46",
          900: "#064e3b",
        },
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "inverse-primary": "#6bd8cb",
        "on-secondary-container": "#5c647a",
        "primary-container": "#008378",
        "outline-variant": "#bcc9c6",
        "secondary-container": "#dae2fd",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00201d",
        "on-surface": "#0b1c30",
        secondary: "#565e74",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#6b7775",
        surface: "#f8f9ff",
        "tertiary-fixed-dim": "#bcc9c6",
        "inverse-surface": "#213145",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed-variant": "#3d4947",
        "on-surface-variant": "#3d4947",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#121e1c",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        tertiary: "#525e5c",
        "on-primary-container": "#f4fffc",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "on-primary-fixed-variant": "#005049",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d3e4fe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        md: "24px",
        base: "4px",
        sm: "16px",
        "margin-mobile": "20px",
        xl: "64px",
        lg: "40px",
        xs: "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-xl-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
